# dbt Project Configuration

name: 'supply_chain_analytics'
version: '1.0.0'
config-version: 2

# Profile to use (references profiles.yml)
profile: 'supply_chain_analytics'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  supply_chain_analytics:
    # Staging models (raw → cleansed)
    staging:
      +materialized: view
      +schema: staging
    
    # Mart models (dimensional models)
    marts:
      +materialized: table
      +schema: marts
